# Generated by Django 5.2.3 on 2025-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_surf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(blank=True, to='escuela_surf.clase'),
        ),
    ]
